_commit: c429cf1
_src_path: gh:bswck/skeleton
author_full_name: Bartosz Sławecki
email_address: bswck.dev@gmail.com
github_username: bswck
license_name: MIT
package_name: proxyvars
project_description: A simple and straight-forward Python module for creating context-dependent
    proxy objects.
publish_on_pypi: true
pypi_project_description: A simple and straight-forward Python module for creating
    context-dependent proxy objects.
pypi_project_name: proxyvars
python_version: '3.8'
repo_name: proxyvars
use_precommit: true
visibility: public
