_commit: 0.0.2rc-234-gca605f0
_src_path: gh:bswck/skeleton
author: bswck
cli: false
copyright: Bartosz Sławecki
description: Callback-based object proxies in Python.
docs: true
email: bartoszpiotrslawecki@gmail.com
github: bswck
license: MIT
package: proxyvars
precommit: true
pypi: true
pypi_description: Callback-based object proxies in Python.
pypi_project: proxyvars
pypy: true
python: '3.8'
python_until: ''
repo: proxyvars
rtd: proxyvars
tests: true
tidelift: true
visibility: public
wip: false
