name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy pylint pytest pytest-lazy-fixture
    - name: Type-check with mypy
      run: >-
        mypy commonvars/ --strict
    - name: Check with black
      run: >-
        black --check commonvars/
    - name: Analyse the code with pylint
      run: >-
        pylint commonvars/
    - name: Run tests
      run: >-
        pytest tests/
  